#!/bin/bash
set -e

echo "=== ADA-Pi-System Post-Remove Script ==="

INSTALL_DIR="/usr/local/ada-pi-system"
SYSTEMD_DIR="/etc/systemd/system"

echo "Removing systemd services..."
rm -f $SYSTEMD_DIR/ada-pi-system-ups.service
rm -f $SYSTEMD_DIR/ada-pi-system-network.service
rm -f $SYSTEMD_DIR/ada-pi-system-modem.service
rm -f $SYSTEMD_DIR/ada-pi-system-gps.service
rm -f $SYSTEMD_DIR/ada-pi-system-bluetooth.service
rm -f $SYSTEMD_DIR/ada-pi-system-fan.service
rm -f $SYSTEMD_DIR/ada-pi-system-tacho-monitor.service
rm -f $SYSTEMD_DIR/ada-pi-system-tacho-uploader.service
rm -f $SYSTEMD_DIR/ada-pi-system-logs.service
rm -f $SYSTEMD_DIR/ada-pi-system-web.service

echo "Reloading systemd..."
systemctl daemon-reload

echo "Removing ADA-Pi-System files..."
rm -rf $INSTALL_DIR

echo "=== ADA-Pi-System Removed ==="
